name: firebase_realtime_toolkit
description: Lightweight realtime clients for Firebase RTDB (SSE) and Firestore (Listen gRPC) without full SDKs.
version: 1.0.0
repository: https://github.com/codelessly/FirebaseRealtimeToolkit
homepage: https://github.com/codelessly/FirebaseRealtimeToolkit
issue_tracker: https://github.com/codelessly/FirebaseRealtimeToolkit/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dependencies:
  grpc: ^5.1.0
  protobuf: ^6.0.0
  fixnum: ^1.1.1
  googleapis_auth: ^2.0.0
  http: ^1.2.2

executables:
  rtdb_sse: rtdb_sse
  firestore_listen: firestore_listen
  firestore_write: firestore_write
